//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BACommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public int AdminID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<System.DateTime> ComplateDate { get; set; }
        public Nullable<bool> IsComplate { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public string ProductName { get; set; }
        public int UnitPrice { get; set; }
        public int UnitInStock { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual User User { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
