//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BACommerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int UserID { get; set; }
        [Required(ErrorMessage = "nickname alaný bos birakilamaz.")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Ýsim alaný bos birakilamaz.")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Soyisim alaný bos birakilamaz.")]
        public string LastName { get; set; }
        [EmailAddress(ErrorMessage = "@örnek.com þeklinde giriþ yapýnýz")]
        [Required(ErrorMessage = " Email Boþ geçilemez ")]
        public string Email { get; set; }
        public string Phone { get; set; }
        [Required(ErrorMessage = "Þifre alaný bos birakilamaz.")]
        public string Password { get; set; }
        public Nullable<bool> Status { get; set; }
        public string DGunu { get; set; }
        public string DAyi { get; set; }
        public string DYili { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
